FROM python:3.12

# Set working directory
WORKDIR /app

# Copy requirements file dan install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy semua file dari backend/app ke dalam container
COPY app/ ./app

# Expose port untuk FastAPI
EXPOSE 8000

# Perintah untuk menjalankan aplikasi
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
